# CLIP_LABELS = [
#     "A photo of a portrait", "A photo of an urban landscape", "A photo of architecture",
#     "A photo of a plant", "A photo of a church", "A photo of the night sky",
#     "A photo of nature", "A photo of a mountain", "A photo of a lake",
#     "A photo of the ocean", "A photo of a family", "A photo of food",
#     "A photo of a street scene", "A photo of a child", "A photo of a group of people",
#     "A photo of a forest", "A photo of the sky with clouds", "A photo of a flower",
#     "A photo of a sunset", "A photo of a beach", "A photo of a library"
# ]

# LABEL_DISPLAY = {
#     "A photo of a portrait": "Portrait",
#     "A photo of an urban landscape": "Urban Landscape",
#     "A photo of architecture": "Architecture",
#     "A photo of a plant": "Plant",
#     "A photo of a church": "Church",
#     "A photo of the night sky": "Night Sky",
#     "A photo of nature": "Nature",
#     "A photo of a mountain": "Mountain",
#     "A photo of a lake": "Lake",
#     "A photo of the ocean": "Ocean",
#     "A photo of a family": "Family",
#     "A photo of food": "Food",
#     "A photo of a street scene": "Street",
#     "A photo of a child": "Child",
#     "A photo of a group of people": "Group",
#     "A photo of a forest": "Forest",
#     "A photo of the sky with clouds": "Sky",
#     "A photo of a flower": "Flower",
#     "A photo of a sunset": "Sunset",
#     "A photo of a beach": "Beach",
#     "A photo of a library": "Library"
# }


CLIP_LABELS = [
    "A photo of a portrait",
    "A photo of a group of people",
    "A photo of a family",
    "A photo of a child",
    "A photo of an urban landscape",
    "A photo of a rural landscape",
    "A photo of a mountain",
    "A photo of a lake",
    "A photo of the ocean",
    "A photo of a beach",
    "A photo of a forest",
    "A photo of a waterfall",
    "A photo of architecture",
    "A photo of a church",
    "A photo of a library",
    "A photo of a garden",
    "A photo of a flower",
    "A photo of food",
    "A photo of a street scene",
    "A photo of the night sky",
    "A photo of a sunset",
    "A photo of a city skyline",
    "A photo of a bridge",
    "A photo of a historic building",
    "A photo of a modern building",
    "A photo of an animal",
    "A photo of wildlife",
    "A photo of a party",
    "A photo of a wedding",
    "A photo of a concert",
    "A photo of a sports event",
    "A photo of a market",
    "A photo of a museum",
    "A photo of a tourist attraction",
    "A photo of a famous landmark",
]

LABEL_DISPLAY = {
    "A photo of a portrait": "Portrait",
    "A photo of a group of people": "Group",
    "A photo of a family": "Family",
    "A photo of a child": "Child",
    "A photo of an urban landscape": "Urban",
    "A photo of a rural landscape": "Rural",
    "A photo of a mountain": "Mountain",
    "A photo of a lake": "Lake",
    "A photo of the ocean": "Ocean",
    "A photo of a beach": "Beach",
    "A photo of a forest": "Forest",
    "A photo of a waterfall": "Waterfall",
    "A photo of architecture": "Architecture",
    "A photo of a church": "Church",
    "A photo of a library": "Library",
    "A photo of a garden": "Garden",
    "A photo of a flower": "Flower",
    "A photo of food": "Food",
    "A photo of a street scene": "Street",
    "A photo of the night sky": "Night Sky",
    "A photo of a sunset": "Sunset",
    "A photo of a city skyline": "Skyline",
    "A photo of a bridge": "Bridge",
    "A photo of a historic building": "Historic Building",
    "A photo of a modern building": "Modern Building",
    "A photo of an animal": "Animal",
    "A photo of wildlife": "Wildlife",
    "A photo of a party": "Party",
    "A photo of a wedding": "Wedding",
    "A photo of a concert": "Concert",
    "A photo of a sports event": "Sports",
    "A photo of a market": "Market",
    "A photo of a museum": "Museum",
    "A photo of a tourist attraction": "Attraction",
    "A photo of a famous landmark": "Landmark",
}